### ISSUE TITLE
ESEA-Rank-Displayer is currently not working 

### ISSUE THREAD

**Issue by abdoomaaz** [meeoh/ESEA-Rank-Displayer#2]
The tool you have made is currently not displaying the ranks, I would say it happend after ESEA's big update, but it was working fine. Are you aware of the issue? I know the tool is made for fun, but it's actually a really nice/helpful tool.

Regards

**Comment by meeoh** [comment]
Thanks for the update @abdoomaaz. Looks like they did something else to their site to break the extension again. I'll check it first thing after work today and their will be a new release by tonight :+1:

**Comment by meeoh** [comment]
Fixed in 580e3b486833a8b4bd390d6d5a57d6f60bba5001 @abdoomaaz 
Please update from the chrome store, you need 1.7! You might need to uninstall/reinstall

**Comment by abdoomaaz** [comment]
Real MVP <3, working like a charm
