### ISSUE TITLE
New ESEA Scoreboard Update

### ISSUE THREAD

**Issue by OliTheMemer** [meeoh/ESEA-Rank-Displayer#3]
The usernames have become more squished together and ranks are sometimes not visible. Maybe change the displayed rank before the userid.

**Comment by meeoh** [comment]
Thanks @OliTheMemer, I'll fix this after work and release an update by the end of today. Would you be able to screenshot how it looks now and post it here?

**Comment by meeoh** [comment]
Just got home and fixed it quick. Put the ranks before the name for now. You should be able to go to the store and update your version of the extension (the fix is 1.8). It might take an hour or so to show up properly in the store though!
