### ISSUE TITLE
Not on FireFox.

### ISSUE THREAD

**Issue by TheOddball** [meeoh/ESEA-Rank-Displayer#4]
Could you maybe port this to FireFox? It takes like 5 seconds to do.

**Comment by meeoh** [comment]
Sure, doing it now :)

Its currently pending review!

**Comment by TheOddball** [comment]
Atleast Mozilla doesn't charge like google does :P

**Comment by meeoh** [comment]
https://addons.mozilla.org/en-US/firefox/addon/esea-ranks-displayer/

@TheOddball all done!

**Comment by TheOddball** [comment]
Thank you very much! <3
